apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-monolith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolith
  template:
    metadata:
      labels:
        app: monolith
    spec:
      serviceAccountName: k8s-firestore-sa # 여기 추가!
      containers:
        - name: gke-monolith
          image: gcr.io/project-460422/gke-monolith:2.0.0
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
